-- Migration: Add market_intelligence column to companies table
-- This column stores the full-site research report generated by the Deep Research feature

DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'companies' 
        AND column_name = 'market_intelligence'
    ) THEN
        ALTER TABLE companies 
        ADD COLUMN market_intelligence TEXT;
        
        RAISE NOTICE 'Added market_intelligence column to companies table';
    ELSE
        RAISE NOTICE 'market_intelligence column already exists';
    END IF;
END $$;
